# Generated by Django 3.0 on 2021-02-13 07:23

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('tenant_name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('domain_url', models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
    ]
